### ISSUE TITLE
App shows "Network is offline" after viewing "My Accounts" and pressing the back button

### ISSUE THREAD

**Issue by baghdadbrian** [zom/Zom-Android-XMPP#411]
This issue seems to occur in other instances when I press back, but I can only repeat it regularly by the method in the title. I can be in the friends list, see a friend, select him, select to send him a message, and no display of the "Network is offline" but when I press "back" in the app sometimes it shows suddenly "Network is offline."

On further review this *sometimes* also seems to happen when pressing the back button on the android device OR the back arrow in the app. Am using the latest version of Zom on a Pixel

**Comment by n8fr8** [comment]
I think this is fixed in our next release.

**Comment by baghdadbrian** [comment]
great, I'll test when I see the new update!

**Comment by varac** [comment]
Bug is still present in Zom Android 15.6.0-beta-3 from June 4th.

**Comment by tiffrobo** [comment]
I don't see this bug in the latest build.

Device: Moto G play, Moto E
OS: Android 6.0.1, Android 5.1
App version: 15.6.0-beta-6
