### ISSUE TITLE
Unable to receive OMEMO encrypted messages with fallback

### ISSUE THREAD

**Issue by kmq** [zom/Zom-Android-XMPP#466]
Scenario
-------------
An OMEMO encrypted message that includes a fallback is received.

Expected
-------------
Zom decrypts the message and ignores the fallback

Actual
----------
Zom shows only the fallback message 
> I have sent you an OMEMO encrypted message, but your client doesn't
> seem to support that.

completely ignoring the encrypted payload.

This makes impossible to communicate with people using the zom.im server, as that server disallows unencrypted communication.

**Comment by n8fr8** [comment]
Got it. I thought we handled this correctly. Looking into it...

**Comment by wiktor-k** [comment]
I'm also experiencing this issue from contacts using Conversations.im

**Comment by tiffrobo** [comment]
@iamironrabbit I don't fully understand the ticket. Can you tell me how to test this one, please?

**Comment by iamironrabbit** [comment]
In short, test using Conversations.im app. If you can receive messages from Conversations to Zom, then it is fixed. So says the rabbit!

**Comment by tiffrobo** [comment]
@iamironrabbit can you test this one, please?

**Comment by wiktor-k** [comment]
I tested this with Zom version 15.5.0-RC-2 and the behavior of Zom is very weird: some messages from Conversations are correctly decrypted but some of them still show the fallback ("I sent you an OMEMO..."). It's hard to me to spot the difference why some of them work and some doesn't but the bug is 100% reproducible.
