### ISSUE TITLE
compiled builds from Zom-Android repo dont connect to server

### ISSUE THREAD

**Issue by froghorn82** [zom/Zom-Android-XMPP#498]
I've compiled all builds using gradle successfully.
I've tested debug, free and zomrelease - all of them dont connect to any server. When attempting to create a Zom ID even home.zom.im says An error occured while connecting to the chat server please check you config and try again.

**Comment by froghorn82** [comment]
anyone??

**Comment by iamironrabbit** [comment]
Do you have a valid certificate on your server?

**Comment by iamironrabbit** [comment]
Also enable debug on the Zom client so you can get more detailed output.

**Comment by froghorn82** [comment]
Yes cert is valid, and it happens on all servers I test besides home.zom.im.
Some servers need CAPTURE to appear for registration but Zom is not showing that and it hangs with the little boy praying forever. His prayers sadly not answered :(

**Comment by abeluck** [comment]
Not sure if this is related, but using the 15.7.0 beta 2 when I attempt to sign in to `staging.zom.im` using an existing account, the app crashes with:

```
11-05 12:53:32.604 28047 28468 E Zom     : auto onboarding fail
11-05 12:53:32.604 28047 28468 E Zom     : java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
11-05 12:53:32.604 28047 28468 E Zom     : 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
11-05 12:53:32.604 28047 28468 E Zom     : 	at java.util.ArrayList.get(ArrayList.java:308)
11-05 12:53:32.604 28047 28468 E Zom     : 	at org.awesomeapp.messenger.ui.onboarding.OnboardingManager.addExistingAccount(OnboardingManager.java:371)
11-05 12:53:32.604 28047 28468 E Zom     : 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.doInBackground(OnboardingActivity.java:806)
11-05 12:53:32.604 28047 28468 E Zom     : 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.doInBackground(OnboardingActivity.java:796)
11-05 12:53:32.604 28047 28468 E Zom     : 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
11-05 12:53:32.604 28047 28468 E Zom     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-05 12:53:32.604 28047 28468 E Zom     : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
11-05 12:53:32.604 28047 28468 E Zom     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-05 12:53:32.604 28047 28468 E Zom     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-05 12:53:32.604 28047 28468 E Zom     : 	at java.lang.Thread.run(Thread.java:818)
11-05 12:53:32.624 28047 28047 D AndroidRuntime: Shutting down VM
11-05 12:53:32.632 28047 28047 E AndroidRuntime: FATAL EXCEPTION: main
11-05 12:53:32.632 28047 28047 E AndroidRuntime: Process: im.zom.messenger, PID: 28047
11-05 12:53:32.632 28047 28047 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.awesomeapp.messenger.ui.onboarding.OnboardingAccount.username' on a null object reference
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.onPostExecute(OnboardingActivity.java:825)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.onPostExecute(OnboardingActivity.java:796)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:175)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5430)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-05 12:53:32.632 28047 28047 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-05 12:53:32.636  2321  5450 W ActivityManager:   Force finishing activity im.zom.messenger/org.awesomeapp.messenger.ui.onboarding.OnboardingActivity
```

**Comment by abeluck** [comment]
with latest build:

```
11-27 11:36:24.255 23503 23660 D Zom     : generating+local+key+pair
11-27 11:36:25.524  4729  4729 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
11-27 11:36:25.536  4729  4729 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48
11-27 11:36:25.974 23503 23660 D Zom     : SUCCESS%21+generating+local+key+pair
11-27 11:36:26.047 23503 23660 E Zom     : auto onboarding fail
11-27 11:36:26.047 23503 23660 E Zom     : java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
11-27 11:36:26.047 23503 23660 E Zom     : 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
11-27 11:36:26.047 23503 23660 E Zom     : 	at java.util.ArrayList.get(ArrayList.java:308)
11-27 11:36:26.047 23503 23660 E Zom     : 	at org.awesomeapp.messenger.ui.onboarding.OnboardingManager.addExistingAccount(OnboardingManager.java:371)
11-27 11:36:26.047 23503 23660 E Zom     : 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.doInBackground(OnboardingActivity.java:806)
11-27 11:36:26.047 23503 23660 E Zom     : 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.doInBackground(OnboardingActivity.java:796)
11-27 11:36:26.047 23503 23660 E Zom     : 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
11-27 11:36:26.047 23503 23660 E Zom     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-27 11:36:26.047 23503 23660 E Zom     : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
11-27 11:36:26.047 23503 23660 E Zom     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-27 11:36:26.047 23503 23660 E Zom     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-27 11:36:26.047 23503 23660 E Zom     : 	at java.lang.Thread.run(Thread.java:818)
11-27 11:36:26.058 23503 23503 D AndroidRuntime: Shutting down VM
11-27 11:36:26.065 23503 23503 E AndroidRuntime: FATAL EXCEPTION: main
11-27 11:36:26.065 23503 23503 E AndroidRuntime: Process: im.zom.messenger, PID: 23503
11-27 11:36:26.065 23503 23503 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.awesomeapp.messenger.ui.onboarding.OnboardingAccount.username' on a null object reference
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.onPostExecute(OnboardingActivity.java:825)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.onPostExecute(OnboardingActivity.java:796)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:175)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5430)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-27 11:36:26.065 23503 23503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-27 11:36:26.068  2321  5433 W ActivityManager: Process im.zom.messenger has crashed too many times: killing!
11-27 11:36:26.071  2321  5433 W ActivityManager:   Force finishing activity im.zom.messenger/org.awesomeapp.messenger.ui.onboarding.OnboardingActivity
```

**Comment by iamironrabbit** [comment]
Hrmph. Looking again.

**Comment by froghorn82** [comment]
All builds (free and zom releases) spit out the following error after entering a username on "Create a Zom ID" page.

`11-29 13:57:20.535 3870-5045/org.awesomeapp.messenger E/Zom: auto onboarding fail
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at org.awesomeapp.messenger.ui.onboarding.OnboardingManager.registerAccount(OnboardingManager.java:285)
        at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$FindServerTask.doInBackground(OnboardingActivity.java:600)
        at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$FindServerTask.doInBackground(OnboardingActivity.java:565)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by iamironrabbit** [comment]
The XmppImPlugin entry class was deleted and removed from the app manifest unintentionally. That's what the 0 array length is, since we look that up to see the possible types of connections we can register for. Fixing...

**Comment by iamironrabbit** [comment]
new build here that should fix this: https://github.com/zom/Zom-Android/releases/tag/15.7.0-RC-3

**Comment by froghorn82** [comment]
@iamironrabbit still not working
`12-04 21:06:18.927 3006-3267/im.zom.messenger E/Zom: error+registering+new+account
    org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS
        at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:272)
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:157)
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:128)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:901)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:409)
        at org.awesomeapp.messenger.plugin.xmpp.XmppConnection.initConnection(XmppConnection.java:2478)
        at org.awesomeapp.messenger.plugin.xmpp.XmppConnection.registerAccount(XmppConnection.java:4488)
        at org.awesomeapp.messenger.ui.onboarding.OnboardingManager.registerAccount(OnboardingManager.java:324)
        at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$FindServerTask.doInBackground(OnboardingActivity.java:600)
        at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$FindServerTask.doInBackground(OnboardingActivity.java:565)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by abeluck** [comment]
@froghorn82  Could you please try again? It's possible we were doing server maintenance during the time you tested.

**Comment by iamironrabbit** [comment]
also timeout of 5s / 5000ms is too low. Changed back to 30s.
